CREATE VIEW UKRDC_VIEW_PROCEDURE
    NULL AS LocalPatientId,
    NULL AS ProcedureTypeCode,
    NULL AS ProcedureTypeCodeStd,
    NULL AS ProcedureTypeDesc,
    NULL AS ClinicianCode,
    NULL AS ClinicianCodeStd,
    NULL AS ClinicianDesc,
    NULL AS ProcedureTime,
    NULL AS EnteredByCode,
    NULL AS EnteredByCodeStd,
    NULL AS EnteredByDesc,
    NULL AS EnteredAtCode,
    NULL AS EnteredAtCodeStd,
    NULL AS EnteredAtDesc,
    NULL AS UpdatedOn,
    NULL AS ActionCode,
    NULL AS ExternalId
    