CREATE VIEW UKRDC_VIEW_TRANSPLANTS AS
SELECT
    NULL AS LocalPatientId,
    NULL AS ProcedureTypeCode,
    NULL AS ProcedureTypeCodeStd,
    NULL AS ProcedureTypeDesc,
    NULL AS ClinicianCode,
    NULL AS ClinicianCodeStd,
    NULL AS ClinicianDesc,
    NULL AS ProcedureTime,
    NULL AS EnteredByCode,
    NULL AS EnteredByCodeStd,
    NULL AS EnteredByDesc,
    NULL AS EnteredAtCode,
    NULL AS EnteredAtCodeStd,
    NULL AS EnteredAtDesc,
    NULL AS UpdatedOn,
    NULL AS ActionCode,
    NULL AS ExternalId
    NULL AS TRA64,
    NULL AS TRA65,
    NULL AS TRA66,
    NULL AS TRA76,
    NULL AS TRA77,
    NULL AS TRA78,
    NULL AS TRA79,
    NULL AS TRA80
