CREATE VIEW UKRDC_VIEW_PATIENT AS   
SELECT 
   NULL AS SendingFacility,
   NULL AS LocalPatientId,
   NULL AS BirthTime,
   NULL AS DeathTime,
   NULL AS Gender,
   NULL AS CountryOfBirth,
   NULL AS EthnicGroup,
   NULL AS Occupation,
   NULL AS PatientLanguage,
   NULL AS Death,
   NULL AS FamilyDoctor_GPPracticeId,
   NULL AS FamilyDoctor_GPId,   
   NULL AS PersonToContactName,
   NULL AS PersonToContact_ContactNumber,
   NULL AS PersonToContact_ContactNumberType,
   NULL AS PersonToContact_Relationship,
   NULL AS UpdatedOn,
   NULL AS ActionCode,
   NULL AS ExternalId
