CREATE VIEW UKRDC_VIEW_DIALYSISSESSION AS
SELECT
    NULL AS LocalPatientId,
    NULL AS ProcedureTypeCode,
    NULL AS ProcedureTypeCodeStd,
    NULL AS ProcedureTypeDesc,
    NULL AS ClinicianCode,
    NULL AS ClinicianCodeStd,
    NULL AS ClinicianDesc,
    NULL AS ProcedureTime,
    NULL AS EnteredByCode,
    NULL AS EnteredByCodeStd,
    NULL AS EnteredByDesc,
    NULL AS EnteredAtCode,
    NULL AS EnteredAtCodeStd,
    NULL AS EnteredAtDesc,
    NULL AS QHD19,
    NULL AS QHD20,
    NULL AS QHD21,
    NULL AS QHD22,
    NULL AS QHD30,
    NULL AS QHD31,
    NULL AS QHD32,
    NULL AS QHD33,
    NULL AS UpdatedOn,
    NULL AS ActionCode,
    NULL AS ExternalId
