CREATE VIEW UKRDC_VIEW_TREATMENT AS
SELECT
    NULL AS LocalPatientId,
    NULL AS EncounterNumber,
    NULL AS EncounterType,
    NULL AS FromTime,
    NULL AS ToTime,
    NULL AS VisitDescription,
    NULL AS AdmittingClinicianCode,
    NULL AS AdmittingClinicianCodeStd,    
    NULL AS AdmittingClinicianDesc,    
    NULL AS AdmitReasonCode,    
    NULL AS AdmitReasonCodeStd,    
    NULL AS AdmitReasonDesc,    
    NULL AS DischargeReasonCode,    
    NULL AS DischargeReasonCodeStd,    
    NULL AS DischargeReasonDesc,
    NULL AS HealthCareFacilityCode,    
    NULL AS HealthCareFacilityCodeStd,    
    NULL AS HealthCareFacilityDesc,    
    NULL AS EnteredAtCode,    
    NULL AS EnteredAtCodeStd,    
    NULL AS EnteredAtDesc,    
    NULL AS UpdatedOn,
    NULL AS ActionCode,
    NULL AS ExternalId,
    NULL AS HDP01,
    NULL AS HDP02,
    NULL AS HDP03,
    NULL AS HDP04,
    NULL AS QBL05,
    NULL AS QBL06,
    NULL AS QBL07,
    NULL AS ERF61,
    NULL AS PAT35

    