CREATE VIEW UKRDC_VIEW_ORDER AS
SELECT
   NULL AS LocalPatientId,
   NULL AS PlacerId,
   NULL AS FillerId,
   NULL AS OrderedByCode,
   NULL AS OrderedByCodeStd,
   NULL AS OrderedByDesc,
   NULL AS OrderedCategoryCode,
   NULL AS OrderedCategoryCodeStd,
   NULL AS OrderedCategoryDesc,
   NULL AS SpecimenSource,
   NULL AS SpecimenReceivedTime,
   NULL AS SpecimenCollectedTime,
   NULL AS Duration,
   NULL AS PatientClassCode,
   NULL AS PatientClassCodeStd,
   NULL AS PatientClassDesc,
   NULL AS EnteredOn,
   NULL AS EnteredAtCode,
   NULL AS EnteredAtCodeStd,
   NULL AS EnteredAtDesc,
   NULL AS UpdatedOn,
   NULL AS ActionCode,
   NULL AS ExternalId
